name: minigame-module-unit-test
main: io.github.inggameteam.plugin.minigame.MinigamePlugin
version: $version
api-version: 1.18
libraries:
  - io.github.inggameteam:inggame-modules:1.0.6
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
  - org.jetbrains.kotlin:kotlin-reflect:1.6.10
