ALREADY_JOINED.chat: "&c이미 %s에 참여했습니다"
CANNOT_JOIN_DUE_TO_STARTED.chat: "&c이미 %s이(가) 시작되서 참여할 수 없습니다"
JOIN: {}
LEFT: {}
START_SPECTATING.chat: "&6넌 지금 %s을(를) 구경하고 있어!"
LEFT_GAME_DUE_TO_SERVER_LEFT: {}
START_CANCELLED_DUE_TO_PLAYERLESS.chat: "&c플레이어가 충분 하지 않아 시작할 수 없습니다"
SINGLE_WINNER.chat: "&6%s %s 승리"
TWO_WINNER.chat: "&6%s %s 승리"
TEAM_WINNER.chat: "&6%s %s 승리"
GAME_START.chat: "&a%s이(가) 시작되었어요!"
NEED_PLAYER.chat: "&7%s을(를) 플레이하려면 최소 %s명의 플레이어가 필요합니다"
GAME_START_COUNT_DOWN.title:
  title: "&e%s %s"
  subTitle: ""
  fadeIn: 0
  stay: 25
  fadeOut: 0
RED_TEAM_WIN.chat: "&6레드팀 %s 승리"
BLUE_TEAM_WIN.chat: "&6블루팀 %s 승리"
PLAYER_DEATH_TO_VOID.chat: "&c%s&c이(가) 사망했습니다"
GAME_DRAW_HAS_WINNER.chat: "&6%s&6 %s&6 무승부"
GAME_DRAW_NO_WINNER.chat: "&6%s&6 무승부"
