PARTY_CREATED.chat: |
  &6--------------------------------------------------
  &a파티가 생성되었습니다
  &a/p <파티에 초대할 플레이어>
  &a/p all
  &6--------------------------------------------------
PARTY_DISBANDED.chat: "&c%s&c이(가) 해산되었습니다"
JOIN_PARTY.chat: "&a%s&a이(가) %s&a에 참여했습니다"
LEFT_PARTY.chat: "&a%s이(가) %s&a를 떠났습니다"
PARTY_REQUEST.component:
  text: "&6>> -&a%s&a이(가) 당신을 %s&a에 초대했습니다! 클릭!&6- <<"
  click:
    action: RUN_COMMAND
    text: "/p accept %s"
PARTY_REQUEST_TO_ALL.component:
  text: "&6>> -&a%s&a이(가) 여러분을 %s&a에 초대했습니다! 클릭!&6- <<"
  click:
    action: RUN_COMMAND
    text: "/p accept %s"
SENT_PARTY_REQUEST.chat: "&a%s&a에게 %s&a 초대를 보냈습니다"
SENT_PARTY_REQUEST_RECEIVE_ALL.chat: "&a%s&a이(가) %s&a에게 %s&a 초대를 보냈습니다"
SENT_PARTY_REQUEST_TO_ALL.chat: "&a모두에게 %s&a 초대를 보냈습니다"
SENT_PARTY_REQUEST_TO_ALL_RECEIVE_ALL.chat: "&a%s&a이(가) 모두에게 %s&a 초대를 보냈습니다"
PARTY_PROMOTED.chat: "&a%s&a이(가) %s&a의 리더로 위임되었습니다"
PARTY_KICKED.chat: "&a%s&a이(가) %s&a(으)로부터 추방당했습니다"
PARTY_BANNED.chat: "&a%s&a이(가) %s&a(으)로부터 차단당했습니다"
PARTY_UNBANNED.chat: "&a%s&a이(가) %s&a(으)로부터의 차단이 해제되었습니다"
CANNOT_REQUEST_PARTY_DUE_TO_BANNED.chat: "&a%s&a이(가) %s&a(으)로부터 차단되서 초대할 수 없습니다"
PARTY_RENAMED.chat: "&a%s&a이(가) &a%s&a에서 &a%s&a(으)로 개명했습니다"
ONLY_LEADER_START.chat: "&c파티 리더만 미니게임을 실행할 수 있습니다"
PARTY_RENAME_IS_LEADER_ONLY.chat: "&c파티 리더만 파티 이름을 개명할 수 있습니다"
OVER_PARTY_NAME_LENGTH.chat: "&c파티 이름은 20자를 초과할 수 없습니다"
NOW_ANYONE_CAN_JOIN_PARTY.chat: "&a이제 누구나 내 파티에 참여할 수 있습니다"
NOW_CANNOT_JOIN_WITHOUT_INVITE_PARTY.chat: "&a이제 초대한 사람만 내 파티에 참여할 수 있습니다"
CANNOT_PROMOTE_YOURSELF.chat: "&c당신을 리더로 위임할 수는 없습니다"
JOINED_PARTY_NOT_EXIST.chat: "&c참여 중인 파티가 없습니다"
LEADER_PROMOTE_YOU.chat: "&a%s이(가) 당신을 %s 방장으로 위임했습니다"
PARTY_PROMOTE_IS_LEADER_ONLY.chat: "&c파티 리더만 위임할 수 있습니다"
CANNOT_KICK_YOURSELF.chat: "&c자신을 추방할 수는 없습니다"
LEADER_KICKED_YOU.chat: "&a%s이(가) 당신을 %s에서 추방했습니다"
PARTY_KICK_IS_LEADER_ONLY.chat: "&c파티 리더만 추방시킬 수 있습니다"
CANNOT_BAN_YOURSELF.chat: "&c자신을 차단할 수는 없습니다"
LEADER_BANNED_YOU.chat: "&a%s이(가) 당신을 %s에서 차단했습니다"
PARTY_BAN_IS_LEADER_ONLY.chat: "&c파티 리더만 차단할 수 있습니다"
YOU_BANNED_THE_PLAYER.chat: "&c%s이(가) %s에서 차단되었습니다"
CANNOT_UNBAN_YOURSELF.chat: "&c자신을 차단 해제할 수는 없습니다"
THAT_PLAYER_WAS_NOT_BANNED.chat: "&c플레이어가 차단되어 있지 않습니다"
PARTY_UNBAN_IS_LEADER_ONLY.chat: "&c파티 리더만 차단을 해제할 수 있습니다"
PARTY_MEMEBRS.chat: |
  -------------------------------------
  &a파티원(%s명): &6%s
  -------------------------------------
CANNOT_JOIN_DUE_TO_BANNED.chat: "&c이 파티에서 차단되어 참여할 수 없습니다"
YOU_NEED_TO_BE_INVITED_TO_JOIN_PARTY.chat: "&c이 파티에 참여하려면 초대를 받아야 합니다"
PLAYER_NOT_EXIST_IN_PARTY.chat: "&c플레이어가 파티에 없습니다"
