name: Build
on:
  push:
    branches:
      - main
      - develop
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - run: git tag ${{github.run_number}}
      - name: Execute Gradle build
        run: ./gradlew :modules:shadowJar :plugins:shadowJar

      - id: is-prerelease
        run: |
          if [ ${{ github.head_ref }} == 'main' ]
          then
          IS_PRE='false'
          else
          IS_PRE='true'
          fi
          echo "::set-output name=value::IS_PRE"

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build#${{github.run_number}}"
          automatic_release_tag: "${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: plugins/build/dist/*.jar
          prerelease: "${{ steps.is-prerelease.outputs.value }}"
