on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

name: docs to gh pages

jobs:
  build_and_commit:
    name: docs to gh pages
    runs-on: ubuntu-latest
#    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
