name: doctave
on:
  push:
    branches:
      - master
    paths:
      - 'site/**'
jobs:
  gradle:
    #    runs-on: self-hosted
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/Doctave/doctave --tag 0.4.2
      - name: start docative intialize
        run: doctave init
      - name: start docative intialize
        run: doctave build --release
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: no-reply@github.com
          build_dir: site
          branch: gh-pages
          jekyll: no
          commit_message: custom message # optional
