name: Run Gradle on PRs
on:
  pull_request:
    branches:
      - release
jobs:
  gradle:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew :inggame-plugins:jar

        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release #${{ env.workflow }}"
          automatic_release_tag: latest
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: inggame-plugins/build/dist/*.jar
          prerelease: false
