name: Run Gradle
on:
  push:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew :modules:shadowJar :plugins:shadowJar

      - name: tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "::set-output name=value::$RELEASE_VERSION"

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.tag.outputs.value }}"
          message: ""

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build ${{ steps.tag.outputs.value }}"
          automatic_release_tag: "Build ${{ steps.tag.outputs.value }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: plugins/build/dist/*.jar
          prerelease: false
