name: merge docs
on:
  pull_request:
    types: [labeled, opened]
jobs:
  merge-branch:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test1
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: docs
          github_token: "${{ secrets.GITHUB_TOKEN }}"
