name: Run Gradle on PRs
on:
  push:
    branches:
      - master
jobs:
  gradle:
#    runs-on: self-hosted
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v9
        id: verify-changed-files
        with:
          files: |
            docs/*

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: docs
          delete-branch: false
          title: 'update docs'
          labels: |
            automated pr
          draft: false

        # Outputs: "Changed files: new.txt test_directory/new.txt"
