name: pr docs
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "docs"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge staging -> docs
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: docs
          github_token: ${{ github.token }}
