name: pr docs
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_label: "automerge"
          destination_branch: "docs"
          github_token: ${{ secrets.GITHUB_TOKEN }}
